### ISSUE TITLE
Can't add TR.Stride to my own project

### ISSUE THREAD

**Issue by NicusorN5** [johang88/TR.Stride#11]
Hi, I was attempting to include TR.Stride, but after multiple attempts I get this log: https://pastebin.com/JKMmZPvz

After trying to include the project, the editor is unusable.

Steps to reproduce:
1.) Create a new blank Stride project.
2.) In `Solution Explorer` 
- Add existing project
- Add `TR.Stride` from the `TR.Stride` folder

3.) Wait for errors and a possible crash, with the same inner exception as in the given log. May appear immediately after the solution is being loaded, or when attempting to add a new object.

Update: TR.Stride works perfectly when loaded separately as a Stride project.

**Comment by NicusorN5** [comment]
When trying to add `TR.Stride.Common` I get this log
```
Verbose: Process dependencies for TR.Stride.Common...
Verbose: Restore NuGet packages for TR.Stride.Common...
Error: Error while loading assembly reference [D:\Dev\TR Stride\TR.Stride.Common\bin\Debug\net6.0\TR.Stride.Common.dll]
TypeInitializationException: The type initializer for '<Module>' threw an exception.
 ---> NotSupportedException: This type of CollectionView does not support changes to its SourceCollection from a thread different from the Dispatcher thread.
   at System.Windows.Data.CollectionView.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs args)
   at Stride.Core.Presentation.Collections.ObservableList`1.OnCollectionChanged(NotifyCollectionChangedEventArgs arg) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\presentation\Stride.Core.Presentation\Collections\ObservableList.cs:line 190
   at Stride.Assets.Presentation.AssetEditors.GraphicsCompositorEditor.ViewModels.GraphicsCompositorEditorViewModel.UpdateAvailableTypes() in C:\BuildAgent\work\b5f46e3c4829a09e\sources\editor\Stride.Assets.Presentation\AssetEditors\GraphicsCompositorEditor\ViewModels\GraphicsCompositorEditorViewModel.cs:line 532
   at Stride.Assets.Presentation.AssetEditors.GraphicsCompositorEditor.ViewModels.GraphicsCompositorEditorViewModel.AssembliesUpdated(Object sender, AssemblyRegisteredEventArgs e) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\editor\Stride.Assets.Presentation\AssetEditors\GraphicsCompositorEditor\ViewModels\GraphicsCompositorEditorViewModel.cs:line 378
   at Stride.Core.Reflection.AssemblyRegistry.OnAssemblyRegistered(Assembly assembly, HashSet`1 categories) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\core\Stride.Core\Reflection\AssemblyRegistry.cs:line 292
   at Stride.Core.Reflection.AssemblyRegistry.Register(Assembly assembly, IEnumerable`1 categories) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\core\Stride.Core\Reflection\AssemblyRegistry.cs:line 237
   at Stride.Core.Reflection.AssemblyRegistry.Register(Assembly assembly, String[] categories) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\core\Stride.Core\Reflection\AssemblyRegistry.cs:line 253
   at Stride.Core.DataSerializers.TR_Stride_CommonSerializerFactory.Initialize()
   at .cctor()
   at System.Runtime.CompilerServices.RuntimeHelpers.RunModuleConstructor(ModuleHandle module)
   at Stride.Core.Reflection.AssemblyContainer.LoadAssemblyFromPathInternal(String assemblyFullPath) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\core\Stride.Core.Design\Reflection\AssemblyContainer.cs:line 350

Error: Unable to load assembly reference [D:\Dev\TR Stride\TR.Stride.Common\bin\Debug\net6.0\TR.Stride.Common.dll]
Verbose: Loading Assets from Package [TR.Stride.Common.sdpkg]
```

**Comment by NicusorN5** [comment]
Nevermind, I had to add the project in Visual Studio, and set the references so the assets and scripts are loaded in the correct order.
